server:
  port: 8080
  compression:
    enabled: true
    excluded-user-agents: gozilla,traviata
    mime-types: text/html,text/xml,text/plain,text/css,apply/json
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
  max-http-header-size: 10485760
spring:
  application:
    name: springboot-2-mybatis-seed
  profiles:
    active: pro
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: true
    static-path-pattern: /**
  resources:
    add-mappings: false
    static-locations: classpath:/static/
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        min-idle: 1
        max-wait: 60000ms
        max-active: 8
      shutdown-timeout: 100ms
    password: Jovaunn1
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
    #jdbc:
    #initialize-schema: never
mybatis:
  type-aliases-package: isa.qa.project.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:mapper/*/*Mapper.xml