server:
  port: 8080
  compression:
    enabled: true
    excluded-user-agents: gozilla,traviata
    mime-types: text/html,text/xml,text/plain,text/css,apply/json
  tomcat:
    max-threads: 100
    uri-encoding: UTF-8
spring:
  application:
    name: springboot-2-mybatis-seed
  profiles:
    active: pro
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: true
    static-path-pattern: /**
  resources:
    add-mappings: false
    static-locations: classpath:/static/
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-idle: 8
        min-idle: 1
        max-wait: 60000ms
        max-active: 8
      shutdown-timeout: 100ms
    password: Jovaunn1
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
    #jdbc:
    #initialize-schema: never
mybatis:
  type-aliases-package: isa.qa.project.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:mapper/*/*Mapper.xml
mapper:
  #通用Mapper接口
  mappers: isa.qa.project.base.BaseMapper
  not-empty: false
  identity: MYSQL
uid:
  timeBits: 30             # 时间位, 默认:30
  workerBits: 16           # 机器位, 默认:16
  seqBits: 7               # 序列号, 默认:7
  epochStr: "2019-02-20"   # 初始时间, 默认:"2019-02-20"
  enableBackward: true    # 是否容忍时钟回拨, 默认:true
  maxBackwardSeconds: 1    # 时钟回拨最长容忍时间（秒）, 默认:1
  CachedUidGenerator:     # CachedUidGenerator相关参数
    boostPower: 3          # RingBuffer size扩容参数, 可提高UID生成的吞吐量, 默认:3
    paddingFactor: 50      # 指定何时向RingBuffer中填充UID, 取值为百分比(0, 100), 默认为50
    #scheduleInterval: 60    # 默认:不配置此项, 即不实用Schedule线程. 如需使用, 请指定Schedule线程时间间隔, 单位:秒